- name: Launch EC2 instance
  ec2:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image_id }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    wait: yes
    count: 1
    instance_tags:
      Name: AnsibleEC2
  register: ec2_instances

- name: Output instance details
  debug:
    var: ec2_instances