- name: Launch EC2 instance
  ec2:
    key_name: my-key
    instance_type: t2.micro
    image: ami-0c02fb55956c7d316
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    wait: yes
    count: 1
    instance_tags:
      Name: AnsibleEC2
  register: ec2_instances

- name: Output instance details
  debug:
    var: ec2_instances
